### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [misantron/dbunit#2]
@misantron, thanks for your forked DBUnit and work on this.

Actually, I also found the replacement of ` sebastianbergmann/dbunit` package.

Is this going to be the maintained/active `DBUnit` package ❓ 

Thanks.

**Comment by misantron** [comment]
@peter279k this fork is just to migrate my project to PHPUnit 8. I don't plan to maintain original packages `sebastianbergmann/dbunit` or `phpunit/dbunit` but want to make a couple minor releases of my fork to increase tests code coverage and cleanup code base.

**Comment by peter279k** [comment]
@misantron, thanks for your explanation.

It seems that you want keep your existed repository that use `DBUnit` can be compatible with PHPUnit 8.

This issue is going to be closed because of your straightforward reply :).
